import Layout from '@/components/Layout';
import Loader from '@/components/loader/Loader';
import '@/styles/globals.css';
import Head from 'next/head';
import { Router, useRouter } from 'next/router';
import { useEffect, useState } from 'react';

export default function App({ Component, pageProps }) {
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    Router.events.on('routeChangeStart', url => {
      setIsLoading(true);
    });

    Router.events.on('routeChangeComplete', url => {
      setIsLoading(false);
    });

    Router.events.on('routeChangeError', url => {
      setIsLoading(false);
    });
  }, []);

  const router = useRouter();
  const { locale } = router;

  useEffect(() => {
    if (localStorage.theme === 'dark') {
      document.documentElement.classList.add('dark');
    }
  });

  return (
    <>
      <Head>
        <title>
          {locale === 'en'
            ? 'Sawwweb - ' + Component.titleEn
            : 'Sawwweb - ' + Component.titleRu}
        </title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.png' />
      </Head>
      {isLoading && <Loader />}
      <Layout>
        <Component {...pageProps} locale={locale} />
      </Layout>
    </>
  );
}
